---
title: "Shiny group work sheet "
author: "Eda Emanet"
date: "07 01 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message=FALSE}
library(jsonlite)
df1<-fromJSON("son_medical.json")

df2<-fromJSON("son_bio.json")

df3 <- fromJSON("son_gene.json")

df1<- as.data.frame(df1)
df2 <- as.data.frame(df2)
data1<- data.frame(df1,df2)

```


```{r}
library(MSMB)
library(EBImage)
library(tiff)

library("EBImage")

img = readImage("C:/Users/Dell/Dropbox/My PC (DESKTOP-EB8G4PC)/Desktop/yes/Y1.jpg")
img1 = readImage("C:/Users/Dell/Dropbox/My PC (DESKTOP-EB8G4PC)/Desktop/yes/Y2.jpg")
img2 = readImage("C:/Users/Dell/Dropbox/My PC (DESKTOP-EB8G4PC)/Desktop/yes/Y3.jpg")
img4 = readImage("C:/Users/Dell/Dropbox/My PC (DESKTOP-EB8G4PC)/Desktop/yes/Y4.jpg")
img11 = readImage("C:/Users/Dell/Dropbox/My PC (DESKTOP-EB8G4PC)/Desktop/yes/Y11.jpg")
img6 = readImage("C:/Users/Dell/Dropbox/My PC (DESKTOP-EB8G4PC)/Desktop/yes/Y6.jpg")
img7 = readImage("C:/Users/Dell/Dropbox/My PC (DESKTOP-EB8G4PC)/Desktop/yes/Y7.jpg")
img8 = readImage("C:/Users/Dell/Dropbox/My PC (DESKTOP-EB8G4PC)/Desktop/yes/Y8.jpg")
img9 = readImage("C:/Users/Dell/Dropbox/My PC (DESKTOP-EB8G4PC)/Desktop/yes/Y9.jpg")
display(img)
display(img1)
display(img2)
display(img4)
display(img11)
display(img6)
display(img7)
display(img8)
display(img9)
```

```{r}
library(utf8)
library(lubridate)
library(tidyverse)
library(dplyr)
attach(df1)

df1$demographic <- df1$demographic %>%
                 mutate_if(is.character,as.factor)

df1$demographic$year_of_death <-as.Date(as.character(demographic$year_of_death),format="%Y")

class(df1$demographic$year_of_death)

df1$demographic$year_of_birth<-as.Date(as.character(demographic$year_of_birth),format="%Y")
class(df1$demographic$year_of_birth)

df1$demographic <- df1$demographic[,-c(14:17,8)]


data1 <- data.frame(df1,df2)
```













